local vscode = require("vscode-neovim")

vim.notify = vscode.notify

vim.opt.scrolloff = 999

vim.keymap.set({ "n", "x" }, "gs", function() vscode.action("workbench.action.gotoSymbol") end)
vim.keymap.set({ "n", "x" }, "<leader>o", function() vscode.action("workbench.action.gotoSymbol") end)
vim.keymap.set({ "n", "x" }, "gS", function() vscode.action("workbench.action.showAllSymbols") end)
vim.keymap.set({ "n", "x" }, "<leader>O", function() vscode.action("workbench.action.showAllSymbols") end)
vim.keymap.set({ "n", "x" }, "gr", function() vscode.action("editor.action.referenceSearch.trigger") end)
vim.keymap.set("n", "]h", function() vscode.action("workbench.action.editor.nextChange") end)
vim.keymap.set("n", "[h", function() vscode.action("workbench.action.editor.previousChange") end)
vim.keymap.set("n", "]d", function() vscode.action("editor.action.marker.next") end)
vim.keymap.set("n", "[d", function() vscode.action("editor.action.marker.prev") end)
vim.keymap.set("n", "<leader>ui", function() vscode.action("editor.action.inspectTMScopes") end)
vim.keymap.set("n", "<leader>ff", function() vscode.action("workbench.action.quickOpen") end)
vim.keymap.set("n", "<leader>fr", function() vscode.action("workbench.action.openRecent") end)
vim.keymap.set("n", "<leader>ks", function() vscode.action("workbench.action.openGlobalKeybindings") end)
vim.keymap.set("n", "<leader>z", function() vscode.action("workbench.action.toggleZenMode") end)
vim.keymap.set("n", "<C-n>", "mciw*<Cmd>nohl<CR>", { remap = true })
vim.keymap.set("n", "]z", function() vscode.action("editor.gotoNextFold") end)
vim.keymap.set("n", "[z", function() vscode.action("editor.gotoPreviousFold") end)
vim.keymap.set("x", "zf", function() vscode.action("editor.createFoldingRangeFromSelection") end)
vim.keymap.set("n", "z.", function() vscode.action("editor.removeManualFoldingRanges") end)
vim.keymap.set("n", "za", function() vscode.action("editor.toggleFold") end)
vim.keymap.set("n", "zc", function() vscode.action("editor.fold") end)
vim.keymap.set("n", "zC", function() vscode.action("editor.foldRecursively") end)
vim.keymap.set("n", "zo", function() vscode.action("editor.unfold") end)
vim.keymap.set("n", "zO", function() vscode.action("editor.unfoldRecursively") end)
vim.keymap.set("n", "zM", function() vscode.action("editor.foldAll") end)
vim.keymap.set("n", "zR", function() vscode.action("editor.unfoldAll") end)
vim.keymap.set("n", "z1", function() vscode.action("editor.foldLevel1") end)
vim.keymap.set("n", "z2", function() vscode.action("editor.foldLevel2") end)
vim.keymap.set("n", "z3", function() vscode.action("editor.foldLevel3") end)
vim.keymap.set("n", "z4", function() vscode.action("editor.foldLevel4") end)
vim.keymap.set("n", "z5", function() vscode.action("editor.foldLevel5") end)
vim.keymap.set("n", "z6", function() vscode.action("editor.foldLevel6") end)
vim.keymap.set("n", "z7", function() vscode.action("editor.foldLevel7") end)
